### ISSUE TITLE
Most images fail to download, instead get empty files

### ISSUE THREAD

**Issue by PFCKrutonium** [ostrolucky/Simple-Subreddit-Image-Downloader#1]
Which are 403's from i.redditmedia.com.

https://i.redditmedia.com/z_AqWdedEtb0S2Vhtoqo23f2yqb3EsGrIaPu_Niu5bU.jpg?fit=crop&amp;crop=faces%2Centropy&amp;arh=2&amp;w=320&amp;s=901c5ae151a351bc8d8ad0996d87a21e:
2017-06-17 03:43:38 ERROR 403: Forbidden.

Example Output.

**Comment by ostrolucky** [comment]
Thanks for letting me know. It's a long time since I used this so I wouldn't know. Should be fixed now.
