### ISSUE TITLE
rid fork

### ISSUE THREAD

**Issue by pirate486743186** [ostrolucky/Simple-Subreddit-Image-Downloader#12]
the rid fork added some polish to the script. Even the name and README is better...  and there's even an AUR package.
https://github.com/dbeley/rid

Unfortunately he didn't fix the breakage yet. He probably didn't notice.

Why you don't merge them. It's silly to ignore each other like this, it should be all in one repo.

**Comment by ostrolucky** [comment]
I didn't know about that fork, nobody reached out to me until you created this issue. I'll merge the improvements

**Comment by ostrolucky** [comment]
Done. Feel free to try it out and let me know if you still miss something.
