### ISSUE TITLE
Getting:  parse error: Invalid numeric literal at line 1, column 10

### ISSUE THREAD

**Issue by Luvirini** [ostrolucky/Simple-Subreddit-Image-Downloader#16]
On running: ./download-subreddit-images.sh battlemaps new all 50
I get the following:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1486  100  1486    0     0  99066      0 --:--:-- --:--:-- --:--:-- 99066
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10

Running on:
Ubuntu 20.04.6 LTS
with jq: 1.6-1ubuntu0.20.04.1
and curl: 7.68.0-1ubuntu2.22

**Comment by ostrolucky** [comment]
It works for me. It probably has nothing to with the script, but your network connectivity. My guess would be you are using proxy, corporate firewall, vpn or something like that, which blocks this. What do you get when you run
```
curl https://www.reddit.com/r/battlemaps/new/.json?raw_json=1&t=all
```
?

**Comment by Luvirini** [comment]
I am not using anything special like that, running the script on linux server I control with a very basic FW policy and no proxy/vpn or such.

Seems that Reddit is blocking the connection for some reason. So I have to check into that. 

----------

<!doctype html>
     <html>
  <head>
    <title>Blocked</title>
    <style>
      body {
          font: small verdana, arial, helvetica, sans-serif;
          width: 600px;
          margin: 0 auto;
      }

      h1 {
          height: 40px;
          background: transparent url(//www.redditstatic.com/reddit.com.header.png) no-repeat scroll top right;
      }
    </style>
  </head>
  <body>
    <h1>whoa there, pardner!</h1>

<p>Your request has been blocked due to a network policy.</p>

<p>Try logging in or creating an account <a href=https://www.reddit.com/login/>here</a> to get back to browsing.</p>

<p>If you're running a script or application, please register or sign in with your developer credentials <a href=https://www.reddit.com/wiki/api/>here</a>. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string,
try changing back to default as that can sometimes result in a block.</p>

<p>You can read Reddit's Terms of Service <a href=https://www.reddit.com/wiki/api/>here</a>.</p>

<p>if you think that we've incorrectly blocked you or you would like to discuss
easier ways to get the data you want, please file a ticket <a href=https://support.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21879292693140>here</a>.</p>

<p>when contacting us, please include your ip address which is: <strong>(My IP)</strong> and reddit account</p>
  </body>
</html>

**Comment by ostrolucky** [comment]
We can change the user agent that script uses if you want. But you'll need to play with it and tell me which one works (if any).

**Comment by Luvirini** [comment]
It seems that this is indeed a problem at my/reddit end. I set up a proxy on that server and got the same result,  So I set it up on a different server in a different location and it works. So seems that reddit is blocking the IP

Thanks for you debugging help.

A possible enhancement for a future version would be to give a more understandable error if the returned file is not json.
