### ISSUE TITLE
curl does not know --no-clobber

### ISSUE THREAD

**Issue by Nuube** [ostrolucky/Simple-Subreddit-Image-Downloader#17]
My curl does not know the --no-clobber parameter.  Consequently the download fails. I use a OMV distribution which is

`uname -r
6.1.0-0.deb11.13-amd64`

(I think wget knows --no-clobber)

I believe something alike

```
if ! [ -f  "$subreddit/$newname" ]; then
   curl --retry 3 --output "$subreddit/$newname" $url
   ...
fi
```

would do the trick.

**Comment by ostrolucky** [comment]
You need curl 7.83.0 at least
