### ISSUE TITLE
jq error

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ostrolucky/Simple-Subreddit-Image-Downloader#8]
When running on VaporwaveArt, I get this error:
```
jq: error (at <stdin>:0): null (null) cannot be matched, as it is not a string
jq: error (at <stdin>:0): null (null) cannot be matched, as it is not a string
jq: error (at <stdin>:0): null (null) cannot be matched, as it is not a string
```
It happens repeatedly, always in batches of 3s. Many images are still downloaded though. Maybe it's non-image posts?

**Comment by makeworld-the-better-one** [comment]
Can you explain what adding `?` did?

**Comment by ostrolucky** [comment]
Not sure myself, got it from https://stackoverflow.com/questions/56690455/jq-select-objects-where-value-contains-string-and-value-not-null
