### ISSUE TITLE
Doesn't download gifs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ostrolucky/Simple-Subreddit-Image-Downloader#9]
It appears to only download the reddit preview image, so just a frame from the full gif. I know this might be out of scope, but I'm filing the issue anyway as I'd like to fix this myself at some point.

**Comment by ostrolucky** [comment]
Problem is classic gifs do not really exist on reddit anymore as they are just videos, so it's getting pretty fuzzy to consider it an image

**Comment by ostrolucky** [comment]
Alright I'm open to this. We can rename downloader to Simple-Subreddit-Media-Downloader or something

**Comment by ostrolucky** [comment]
Looks like there are other solutions for this already. https://github.com/w196/rvd Let's stick this project to images then
